name: ONDC:LOG10
versions:
  - id: 1.2.5
    reporting: true
    supportedActions:
      $ref: src/config/LOG10/V-1.2.5/supportedActions/index.yaml
    usecase:
      - name: Logistics (P2P)
        flows: /V-1.2.5/logistics/flows/index.yaml
