name: ONDC:RET10
versions:
  - id: 1.2.0
    reporting: false
    supportedActions:
      $ref: src/config/RET10/v-1.2.0/supportedActions/index.yaml
    usecase:
      - name: GROCERY
        flows: /v-1.2.0/GROCERY/flows/index.yaml
  - id: 1.2.5
    reporting: false
    supportedActions:
      $ref: src/config/RET10/v-1.2.5/supportedActions/index.yaml
    usecase:
      - name: GROCERY
        flows: /v-1.2.5/GROCERY/flows/index.yaml
