name: ONDC:RET14
versions:
  - id: 1.2.0
    reporting: false
    usecase:
      - name: ELECTRONICS
        flows: "./v-1.2.0/ELECTRONICS/flows/index.yaml"
    supportedActions:
      $ref: "src/config/RET14/v-1.2.0/supportedActions/index.yaml"
  - id: 1.2.5
    reporting: false
    usecase:
      - name: ELECTRONICS
        flows: "./v-1.2.5/ELECTRONICS/flows/index.yaml"
    supportedActions:
      $ref: "src/config/RET14/v-1.2.5/supportedActions/index.yaml"
