name: ONDC:RET15
versions:
  - id: 1.2.5
    reporting: false
    supportedActions:
      $ref: src/config/RET15/v-1.2.5/supportedActions/index.yaml
    usecase:
      - name: APPLIANCES
        flows: /v-1.2.5/APPLIANCES/flows/index.yaml
